version: '1.0'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: TestDatabase
    volumes:
      - mongo_data:/data/db
  backend:
    depends_on:
      - mongodb
    build: 
      context: .
    ports:
      - 3002:3002
    environment:
      MONGO_DB_URL: mongodb://mongodb:27017
      MONGO_DB_NAME: TestDatabase
      MONGO_DB_AUTH_COLLECTION_NAME: Authentication
      MONGO_DB_DASHBOARD_COLLECTION_NAME: Dashboard

volumes:
  mongo_data: {}