version: '1.0'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: TestDatabase
    volumes:
      - ./volume/mongodb:/data/db
  backend:
    depends_on:
      - mongodb
    build: ./Backend
    ports:
      - 3002:3002
  frontend:
    depends_on:
      - backend
    build: ./Frontend
    ports:
      - 3000:3000
